# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.namz.com:
  peer0.supplier.namz.com:
  peer1.supplier.namz.com:
  peer0.manufacturer.namz.com:
  peer1.manufacturer.namz.com:
  peer0.distributor.namz.com:
  peer1.distributor.namz.com:

networks:
  byfn:

services:
  orderer.namz.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.namz.com
    container_name: orderer.namz.com
    networks:
      - byfn

  peer0.supplier.namz.com:
    container_name: peer0.supplier.namz.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.supplier.namz.com
    networks:
      - byfn

  peer1.supplier.namz.com:
    container_name: peer1.supplier.namz.com
    extends:
      file:  base/docker-compose-base.yaml
      # using same services so no need to add seperate serice entries
      service: peer1.supplier.namz.com
    networks:
      - byfn

  peer0.manufacturer.namz.com:
    container_name: peer0.manufacturer.namz.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.manufacturer.namz.com
    networks:
      - byfn

  peer1.manufacturer.namz.com:
    container_name: peer1.manufacturer.namz.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.manufacturer.namz.com
    networks:
      - byfn

  peer0.distributor.namz.com:
    container_name: peer0.distributor.namz.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.distributor.namz.com
    networks:
      - byfn

  peer1.distributor.namz.com:
    container_name: peer1.distributor.namz.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.distributor.namz.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # - FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.supplier.namz.com:7051
      - CORE_PEER_LOCALMSPID=supplierMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/supplier.namz.com/peers/peer0.supplier.namz.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/supplier.namz.com/peers/peer0.supplier.namz.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/supplier.namz.com/peers/peer0.supplier.namz.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/supplier.namz.com/users/Admin@supplier.namz.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.namz.com
      - peer0.supplier.namz.com
      - peer1.supplier.namz.com
      - peer0.manufacturer.namz.com
      - peer1.manufacturer.namz.com
      - peer0.distributor.namz.com
      - peer1.distributor.namz.com
    networks:
      - byfn
  